# Generated by Django 5.0.3 on 2024-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuser',
            name='server_id',
            field=models.CharField(max_length=60),
        ),
    ]
